//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolGrades.Resources {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SchoolGrades.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Annulla.
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Chiudi.
        /// </summary>
        public static string Common_Close {
            get {
                return ResourceManager.GetString("Common_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Elimina.
        /// </summary>
        public static string Common_Delete {
            get {
                return ResourceManager.GetString("Common_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore.
        /// </summary>
        public static string Common_Error {
            get {
                return ResourceManager.GetString("Common_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No.
        /// </summary>
        public static string Common_No {
            get {
                return ResourceManager.GetString("Common_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a OK.
        /// </summary>
        public static string Common_OK {
            get {
                return ResourceManager.GetString("Common_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Salva.
        /// </summary>
        public static string Common_Save {
            get {
                return ResourceManager.GetString("Common_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Attenzione.
        /// </summary>
        public static string Common_Warning {
            get {
                return ResourceManager.GetString("Common_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sì.
        /// </summary>
        public static string Common_Yes {
            get {
                return ResourceManager.GetString("Common_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Orologio lezione .
        /// </summary>
        public static string Main_ActivateLessonClock {
            get {
                return ResourceManager.GetString("Main_ActivateLessonClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Anticipo minuti.
        /// </summary>
        public static string Main_AdvanceMinutes {
            get {
                return ResourceManager.GetString("Main_AdvanceMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Alfabetico.
        /// </summary>
        public static string Main_Alphabetical {
            get {
                return ResourceManager.GetString("Main_Alphabetical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Valutaz..
        /// </summary>
        public static string Main_Assess {
            get {
                return ResourceManager.GetString("Main_Assess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a X tutti.
        /// </summary>
        public static string Main_CheckAll {
            get {
                return ResourceManager.GetString("Main_CheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a  X no voti.
        /// </summary>
        public static string Main_CheckNoGrade {
            get {
                return ResourceManager.GetString("Main_CheckNoGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a X nessuno.
        /// </summary>
        public static string Main_CheckNone {
            get {
                return ResourceManager.GetString("Main_CheckNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a X di vendetta.
        /// </summary>
        public static string Main_CheckRevenge {
            get {
                return ResourceManager.GetString("Main_CheckRevenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Spuntare i nomi degli studenti cui aumentare il fattore vendetta.
        /// </summary>
        public static string Main_CheckStudentsForRevenge {
            get {
                return ResourceManager.GetString("Main_CheckStudentsForRevenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Spuntare i nomi degli studenti cui diminuire il fattore vendetta.
        /// </summary>
        public static string Main_CheckStudentsForRevengeDecrease {
            get {
                return ResourceManager.GetString("Main_CheckStudentsForRevengeDecrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a cambio X.
        /// </summary>
        public static string Main_CheckToggle {
            get {
                return ResourceManager.GetString("Main_CheckToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Scegliere una classe.
        /// </summary>
        public static string Main_ChooseClass {
            get {
                return ResourceManager.GetString("Main_ChooseClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Voti classe.
        /// </summary>
        public static string Main_ClassGradesSummary {
            get {
                return ResourceManager.GetString("Main_ClassGradesSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Costretto.
        /// </summary>
        public static string Main_ComeOn {
            get {
                return ResourceManager.GetString("Main_ComeOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a File di configurazione salvato in .
        /// </summary>
        public static string Main_ConfigSaved {
            get {
                return ResourceManager.GetString("Main_ConfigSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Creare un file di testo normale (Sì) od un file per Markdown (No)?.
        /// </summary>
        public static string Main_CreateTextFile {
            get {
                return ResourceManager.GetString("Main_CreateTextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sortegg. o ordin..
        /// </summary>
        public static string Main_Draw {
            get {
                return ResourceManager.GetString("Main_Draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sorteggio od ordinamento fatto!.
        /// </summary>
        public static string Main_DrawDone {
            get {
                return ResourceManager.GetString("Main_DrawDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Allarme fine lezione.
        /// </summary>
        public static string Main_EnableEndLessonWarning {
            get {
                return ResourceManager.GetString("Main_EnableEndLessonWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Probabilità uguali.
        /// </summary>
        public static string Main_EqualProbability {
            get {
                return ResourceManager.GetString("Main_EqualProbability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Creato il file .
        /// </summary>
        public static string Main_FileCreated {
            get {
                return ResourceManager.GetString("Main_FileCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tipo di file.
        /// </summary>
        public static string Main_FileType {
            get {
                return ResourceManager.GetString("Main_FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a cartella.
        /// </summary>
        public static string Main_GivenFolder {
            get {
                return ResourceManager.GetString("Main_GivenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tipo valutazione.
        /// </summary>
        public static string Main_GradeType {
            get {
                return ResourceManager.GetString("Main_GradeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Id classe.
        /// </summary>
        public static string Main_IdClass {
            get {
                return ResourceManager.GetString("Main_IdClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Id allievo.
        /// </summary>
        public static string Main_IdStudent {
            get {
                return ResourceManager.GetString("Main_IdStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sorg.immag..
        /// </summary>
        public static string Main_ImageSourceGroup {
            get {
                return ResourceManager.GetString("Main_ImageSourceGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Lezioni.
        /// </summary>
        public static string Main_Lessons {
            get {
                return ResourceManager.GetString("Main_Lessons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a lezioni.
        /// </summary>
        public static string Main_LessonsPictures {
            get {
                return ResourceManager.GetString("Main_LessonsPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Inizio lezione.
        /// </summary>
        public static string Main_LessonTime {
            get {
                return ResourceManager.GetString("Main_LessonTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Lista finita: sorteggiare.
        /// </summary>
        public static string Main_ListFinished {
            get {
                return ResourceManager.GetString("Main_ListFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Prima voti bassi.
        /// </summary>
        public static string Main_LowGradesFirst {
            get {
                return ResourceManager.GetString("Main_LowGradesFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gruppi.
        /// </summary>
        public static string Main_MakeGroups {
            get {
                return ResourceManager.GetString("Main_MakeGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Minuti durata.
        /// </summary>
        public static string Main_MinutesDuration {
            get {
                return ResourceManager.GetString("Main_MinutesDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Minuto inizio.
        /// </summary>
        public static string Main_MinuteStart {
            get {
                return ResourceManager.GetString("Main_MinuteStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Mancano meno di {0} minuti alla fine della lezione.
        /// </summary>
        public static string Main_MinutesToEnd {
            get {
                return ResourceManager.GetString("Main_MinutesToEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Mosaico.
        /// </summary>
        public static string Main_Mosaic {
            get {
                return ResourceManager.GetString("Main_Mosaic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sorteggio.
        /// </summary>
        public static string Main_MustDraw {
            get {
                return ResourceManager.GetString("Main_MustDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ordinam..
        /// </summary>
        public static string Main_MustSort {
            get {
                return ResourceManager.GetString("Main_MustSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nome visibile.
        /// </summary>
        public static string Main_NameIsVisible {
            get {
                return ResourceManager.GetString("Main_NameIsVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nessun sorteggio o nessuno presente! .
        /// </summary>
        public static string Main_NoDrawNoPresent {
            get {
                return ResourceManager.GetString("Main_NoDrawNoPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Numero voti.
        /// </summary>
        public static string Main_NoOfGrades {
            get {
                return ResourceManager.GetString("Main_NoOfGrades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nessun allievo presente?.
        /// </summary>
        public static string Main_NoStudentPresent {
            get {
                return ResourceManager.GetString("Main_NoStudentPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nessun studente presente!.
        /// </summary>
        public static string Main_NoStudents {
            get {
                return ResourceManager.GetString("Main_NoStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nessuna materia selezionata!.
        /// </summary>
        public static string Main_NoSubjectSelected {
            get {
                return ResourceManager.GetString("Main_NoSubjectSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a n.Allievi.
        /// </summary>
        public static string Main_NumberOfStudents {
            get {
                return ResourceManager.GetString("Main_NumberOfStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Prima voti vecchi.
        /// </summary>
        public static string Main_OldestFirst {
            get {
                return ResourceManager.GetString("Main_OldestFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Voto più vecchio.
        /// </summary>
        public static string Main_OldestGrade {
            get {
                return ResourceManager.GetString("Main_OldestGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Foto visibile.
        /// </summary>
        public static string Main_PhotoVisible {
            get {
                return ResourceManager.GetString("Main_PhotoVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Domande &quot;pop up&quot;.
        /// </summary>
        public static string Main_PopUpQuestionsEnabled {
            get {
                return ResourceManager.GetString("Main_PopUpQuestionsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Scelta domanda.
        /// </summary>
        public static string Main_Question {
            get {
                return ResourceManager.GetString("Main_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Numero casuale.
        /// </summary>
        public static string Main_RandomNumber {
            get {
                return ResourceManager.GetString("Main_RandomNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tremenda vendetta.
        /// </summary>
        public static string Main_RevengeFactor {
            get {
                return ResourceManager.GetString("Main_RevengeFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Decremento del fattore vendetta per ogni allievo spuntato.
        /// </summary>
        public static string Main_RevengeFactorDecrease {
            get {
                return ResourceManager.GetString("Main_RevengeFactorDecrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Incremento del fattore vendetta per ogni allievo spuntato.
        /// </summary>
        public static string Main_RevengeFactorIncrease {
            get {
                return ResourceManager.GetString("Main_RevengeFactorIncrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a F.V..
        /// </summary>
        public static string Main_RevengeFactorLabel {
            get {
                return ResourceManager.GetString("Main_RevengeFactorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a FV--.
        /// </summary>
        public static string Main_RevengeFactorMinus {
            get {
                return ResourceManager.GetString("Main_RevengeFactorMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a FV++.
        /// </summary>
        public static string Main_RevengeFactorPlus {
            get {
                return ResourceManager.GetString("Main_RevengeFactorPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Materia.
        /// </summary>
        public static string Main_SchoolSubject {
            get {
                return ResourceManager.GetString("Main_SchoolSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cod.Anno.
        /// </summary>
        public static string Main_SchoolYearCode {
            get {
                return ResourceManager.GetString("Main_SchoolYearCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Selezionare una classe.
        /// </summary>
        public static string Main_SelectClass {
            get {
                return ResourceManager.GetString("Main_SelectClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Selezionare un tipo di valutazione.
        /// </summary>
        public static string Main_SelectGradeType {
            get {
                return ResourceManager.GetString("Main_SelectGradeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Selezionare un allievo da valutare.
        /// </summary>
        public static string Main_SelectStudent {
            get {
                return ResourceManager.GetString("Main_SelectStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Selezionare una materia.
        /// </summary>
        public static string Main_SelectSubject {
            get {
                return ResourceManager.GetString("Main_SelectSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Setup.
        /// </summary>
        public static string Main_Setup {
            get {
                return ResourceManager.GetString("Main_Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Immagine casuale.
        /// </summary>
        public static string Main_ShowRandomImage {
            get {
                return ResourceManager.GetString("Main_ShowRandomImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Criteri sorteg. o ordinam..
        /// </summary>
        public static string Main_SortsGroup {
            get {
                return ResourceManager.GetString("Main_SortsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Suoni.
        /// </summary>
        public static string Main_SoundsInColorTimer {
            get {
                return ResourceManager.GetString("Main_SoundsInColorTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a T.barra.
        /// </summary>
        public static string Main_StartBarTimer {
            get {
                return ResourceManager.GetString("Main_StartBarTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a T.colori.
        /// </summary>
        public static string Main_StartColorTimer {
            get {
                return ResourceManager.GetString("Main_StartColorTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Start links.
        /// </summary>
        public static string Main_StartLinks {
            get {
                return ResourceManager.GetString("Main_StartLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Allievo.
        /// </summary>
        public static string Main_Student {
            get {
                return ResourceManager.GetString("Main_Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Voti allievo.
        /// </summary>
        public static string Main_StudentGradesSummary {
            get {
                return ResourceManager.GetString("Main_StudentGradesSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Lista visibile.
        /// </summary>
        public static string Main_StudentsListVisible {
            get {
                return ResourceManager.GetString("Main_StudentsListVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Annotaz..
        /// </summary>
        public static string Main_StudentsNotes {
            get {
                return ResourceManager.GetString("Main_StudentsNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a suspence.
        /// </summary>
        public static string Main_Suspence {
            get {
                return ResourceManager.GetString("Main_Suspence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Parte da finire.
        /// </summary>
        public static string Main_ToComplete {
            get {
                return ResourceManager.GetString("Main_ToComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Abilita orologio a colori per bottone lezione.
        /// </summary>
        public static string Main_Tooltip_ActivateLessonClock {
            get {
                return ResourceManager.GetString("Main_Tooltip_ActivateLessonClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ordinamento alfabetico.
        /// </summary>
        public static string Main_Tooltip_Alphabetical {
            get {
                return ResourceManager.GetString("Main_Tooltip_Alphabetical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Check tutti allievi.
        /// </summary>
        public static string Main_Tooltip_CheckAll {
            get {
                return ResourceManager.GetString("Main_Tooltip_CheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Check allievi che non hanno voti.
        /// </summary>
        public static string Main_Tooltip_CheckNoGrade {
            get {
                return ResourceManager.GetString("Main_Tooltip_CheckNoGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Check nessun allievo.
        /// </summary>
        public static string Main_Tooltip_CheckNone {
            get {
                return ResourceManager.GetString("Main_Tooltip_CheckNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Fattore vendetta per allievi checked.
        /// </summary>
        public static string Main_Tooltip_CheckRevenge {
            get {
                return ResourceManager.GetString("Main_Tooltip_CheckRevenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cambia check di tutti gli allievi.
        /// </summary>
        public static string Main_Tooltip_CheckToggle {
            get {
                return ResourceManager.GetString("Main_Tooltip_CheckToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Classi dell&apos;anno scolastico selezionato.
        /// </summary>
        public static string Main_Tooltip_ClassesList {
            get {
                return ResourceManager.GetString("Main_Tooltip_ClassesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Finestra di riepilogo dei voti della classe corrente.
        /// </summary>
        public static string Main_Tooltip_ClassGradesSummary {
            get {
                return ResourceManager.GetString("Main_Tooltip_ClassGradesSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Scelta del prossimo allievo dell&apos;elenco.
        /// </summary>
        public static string Main_Tooltip_ComeOn {
            get {
                return ResourceManager.GetString("Main_Tooltip_ComeOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Fa l&apos;ordinamento od il sorteggio.
        /// </summary>
        public static string Main_Tooltip_Draw {
            get {
                return ResourceManager.GetString("Main_Tooltip_Draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sorteggio con uguali probabilitàfra ogni allievo.
        /// </summary>
        public static string Main_Tooltip_EqualProbability {
            get {
                return ResourceManager.GetString("Main_Tooltip_EqualProbability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Estrazione fra le immmagini che stanno sotto la cartella data.
        /// </summary>
        public static string Main_Tooltip_GivenFolder {
            get {
                return ResourceManager.GetString("Main_Tooltip_GivenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Scelta del tipo di voto.
        /// </summary>
        public static string Main_Tooltip_GradeType {
            get {
                return ResourceManager.GetString("Main_Tooltip_GradeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cartella in cui trovare l&apos;immagine casuale (click per aprire un file nella cartella) .
        /// </summary>
        public static string Main_Tooltip_ImagesPath {
            get {
                return ResourceManager.GetString("Main_Tooltip_ImagesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Finestra gestione lezioni della  materia selezionata.
        /// </summary>
        public static string Main_Tooltip_Lessons {
            get {
                return ResourceManager.GetString("Main_Tooltip_Lessons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Estrazione fra  le immagini mostrate durante le lezioni.
        /// </summary>
        public static string Main_Tooltip_LessonsPictures {
            get {
                return ResourceManager.GetString("Main_Tooltip_LessonsPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Colorazione in base al tempo che manca alla fine della lezione.
        /// </summary>
        public static string Main_Tooltip_LessonTime {
            get {
                return ResourceManager.GetString("Main_Tooltip_LessonTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ordinamento per voto descrescente.
        /// </summary>
        public static string Main_Tooltip_LowGradesFirst {
            get {
                return ResourceManager.GetString("Main_Tooltip_LowGradesFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Formazione dei gruppi.
        /// </summary>
        public static string Main_Tooltip_MakeGroups {
            get {
                return ResourceManager.GetString("Main_Tooltip_MakeGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Visualizzazione di tutte le foto della classe.
        /// </summary>
        public static string Main_Tooltip_Mosaic {
            get {
                return ResourceManager.GetString("Main_Tooltip_Mosaic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Visualizza il nome dell&apos;allievo.
        /// </summary>
        public static string Main_Tooltip_NameIsVisible {
            get {
                return ResourceManager.GetString("Main_Tooltip_NameIsVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ordinamento in base al numero dei voti del tipo selezionato.
        /// </summary>
        public static string Main_Tooltip_NoOfGrades {
            get {
                return ResourceManager.GetString("Main_Tooltip_NoOfGrades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ordinamento con prima i voti più vecchi del tipo selezionato.
        /// </summary>
        public static string Main_Tooltip_OldestFirst {
            get {
                return ResourceManager.GetString("Main_Tooltip_OldestFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sceglie l&apos;allievo che ha il voto più vecchio.
        /// </summary>
        public static string Main_Tooltip_OldestGrade {
            get {
                return ResourceManager.GetString("Main_Tooltip_OldestGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Scelta cartella immagini.
        /// </summary>
        public static string Main_Tooltip_PathButton {
            get {
                return ResourceManager.GetString("Main_Tooltip_PathButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Visualizza la foto dell&apos;allievo.
        /// </summary>
        public static string Main_Tooltip_PhotoVisible {
            get {
                return ResourceManager.GetString("Main_Tooltip_PhotoVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Scelta domanda &quot;di default&quot; da fare a tutti.
        /// </summary>
        public static string Main_Tooltip_Question {
            get {
                return ResourceManager.GetString("Main_Tooltip_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Testo della domanda corrente.
        /// </summary>
        public static string Main_Tooltip_QuestionText {
            get {
                return ResourceManager.GetString("Main_Tooltip_QuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Visualizzazione di un&apos;immagine casuale dalla cartella  qui sotto.
        /// </summary>
        public static string Main_Tooltip_RandomNumber {
            get {
                return ResourceManager.GetString("Main_Tooltip_RandomNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sorteggio con probabilità più alta per maggiori fattori di vendetta.
        /// </summary>
        public static string Main_Tooltip_RevengeFactor {
            get {
                return ResourceManager.GetString("Main_Tooltip_RevengeFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Decremento del fattore di vendetta.
        /// </summary>
        public static string Main_Tooltip_RevengeFactorMinus {
            get {
                return ResourceManager.GetString("Main_Tooltip_RevengeFactorMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Aumento del fattore di vendetta.
        /// </summary>
        public static string Main_Tooltip_RevengeFactorPlus {
            get {
                return ResourceManager.GetString("Main_Tooltip_RevengeFactorPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Scelta materia.
        /// </summary>
        public static string Main_Tooltip_SchoolSubject {
            get {
                return ResourceManager.GetString("Main_Tooltip_SchoolSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Anni scolastici che hanno classi.
        /// </summary>
        public static string Main_Tooltip_SchoolYear {
            get {
                return ResourceManager.GetString("Main_Tooltip_SchoolYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Finestra opzioni di configurazione.
        /// </summary>
        public static string Main_Tooltip_Setup {
            get {
                return ResourceManager.GetString("Main_Tooltip_Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Visualizzazione di un&apos;immagine casuale dalla cartella  qui a lato.
        /// </summary>
        public static string Main_Tooltip_ShowRandomImage {
            get {
                return ResourceManager.GetString("Main_Tooltip_ShowRandomImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Esegue i suoni nel timer a colori.
        /// </summary>
        public static string Main_Tooltip_SoundsInColorTimer {
            get {
                return ResourceManager.GetString("Main_Tooltip_SoundsInColorTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Partenza di un cronometro a barra.
        /// </summary>
        public static string Main_Tooltip_StartBarTimer {
            get {
                return ResourceManager.GetString("Main_Tooltip_StartBarTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Partenza di un cronometro a colori.
        /// </summary>
        public static string Main_Tooltip_StartColorTimer {
            get {
                return ResourceManager.GetString("Main_Tooltip_StartColorTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Lancio dei link e programmi legati alla classe.
        /// </summary>
        public static string Main_Tooltip_StartLinks {
            get {
                return ResourceManager.GetString("Main_Tooltip_StartLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Finestra di riepilogo dei voti e delle annotazioni sull&apos;allievo corrente.
        /// </summary>
        public static string Main_Tooltip_StudentGradesSummary {
            get {
                return ResourceManager.GetString("Main_Tooltip_StudentGradesSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Visualizza l&apos;elenco degli allievi della classe.
        /// </summary>
        public static string Main_Tooltip_StudentsListVisible {
            get {
                return ResourceManager.GetString("Main_Tooltip_StudentsListVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Finestra per assegnare annotazioni di gruppo.
        /// </summary>
        public static string Main_Tooltip_StudentsNotes {
            get {
                return ResourceManager.GetString("Main_Tooltip_StudentsNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Aspetta un po&apos; prima di estrarre, suonando una musica.
        /// </summary>
        public static string Main_Tooltip_Suspence {
            get {
                return ResourceManager.GetString("Main_Tooltip_Suspence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Barra tempo per la risposta, Click  per far partire il cronometro..
        /// </summary>
        public static string Main_Tooltip_TimeProgressBar {
            get {
                return ResourceManager.GetString("Main_Tooltip_TimeProgressBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Apre pagina ricerca argomenti già spiegati nel programma didattico.
        /// </summary>
        public static string Main_Tooltip_TopicsDone {
            get {
                return ResourceManager.GetString("Main_Tooltip_TopicsDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ordinamento secondo il peso totale del tipo di voto selezionato.
        /// </summary>
        public static string Main_Tooltip_WeightsSum {
            get {
                return ResourceManager.GetString("Main_Tooltip_WeightsSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Crea un file con tutti gli argomenti fatti nell&apos;anno scolastico.
        /// </summary>
        public static string Main_Tooltip_YearTopics {
            get {
                return ResourceManager.GetString("Main_Tooltip_YearTopics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Argom. fatti.
        /// </summary>
        public static string Main_TopicsDone {
            get {
                return ResourceManager.GetString("Main_TopicsDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Peso totale dei voti.
        /// </summary>
        public static string Main_WeightsSum {
            get {
                return ResourceManager.GetString("Main_WeightsSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Con il tipo di valutazione scelto non si può fare la media.
        ///Selezionare un tipo di valutazione corretto.
        /// </summary>
        public static string Main_WrongGradeType {
            get {
                return ResourceManager.GetString("Main_WrongGradeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a File arg. anno.
        /// </summary>
        public static string Main_YearTopics {
            get {
                return ResourceManager.GetString("Main_YearTopics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Informazione.
        /// </summary>
        public static string Messages_Information {
            get {
                return ResourceManager.GetString("Messages_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a La lingua è stata cambiata.
        ///Il programma verrà riavviato per applicare le modifiche..
        /// </summary>
        public static string Messages_LanguageChangedRestart {
            get {
                return ResourceManager.GetString("Messages_LanguageChangedRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Chiedi la password.
        /// </summary>
        public static string Setup_AskPassword {
            get {
                return ResourceManager.GetString("Setup_AskPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Backup e gen.file.
        /// </summary>
        public static string Setup_BackupManagement {
            get {
                return ResourceManager.GetString("Setup_BackupManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gestione classi.
        /// </summary>
        public static string Setup_ClassesManagement {
            get {
                return ResourceManager.GetString("Setup_ClassesManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Si è verificato un errore durante il salvataggio della configurazione:.
        /// </summary>
        public static string Setup_ConfigError {
            get {
                return ResourceManager.GetString("Setup_ConfigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a File di configurazione salvato.
        ///
        ///Il programma verrà riavviato per applicare le modifiche..
        /// </summary>
        public static string Setup_ConfigSaved {
            get {
                return ResourceManager.GetString("Setup_ConfigSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Configurazione salvata.
        /// </summary>
        public static string Setup_ConfigSavedTitle {
            get {
                return ResourceManager.GetString("Setup_ConfigSavedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a File dei dati.
        /// </summary>
        public static string Setup_DatabaseFile {
            get {
                return ResourceManager.GetString("Setup_DatabaseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cartella dei dati.
        /// </summary>
        public static string Setup_DatabasePath {
            get {
                return ResourceManager.GetString("Setup_DatabasePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cartella dei documenti.
        /// </summary>
        public static string Setup_DocumentsPath {
            get {
                return ResourceManager.GetString("Setup_DocumentsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cancella config..
        /// </summary>
        public static string Setup_EraseConfig {
            get {
                return ResourceManager.GetString("Setup_EraseConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Form da completare!.
        /// </summary>
        public static string Setup_FormToComplete {
            get {
                return ResourceManager.GetString("Setup_FormToComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cartella delle immagini.
        /// </summary>
        public static string Setup_ImagesPath {
            get {
                return ResourceManager.GetString("Setup_ImagesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Lingua.
        /// </summary>
        public static string Setup_Language {
            get {
                return ResourceManager.GetString("Setup_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cartella config..
        /// </summary>
        public static string Setup_OpenConfigFolder {
            get {
                return ResourceManager.GetString("Setup_OpenConfigFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gestione domande.
        /// </summary>
        public static string Setup_QuestionManagement {
            get {
                return ResourceManager.GetString("Setup_QuestionManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Recover argomenti.
        /// </summary>
        public static string Setup_RecoverTopics {
            get {
                return ResourceManager.GetString("Setup_RecoverTopics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Reset database.
        /// </summary>
        public static string Setup_ResetDatabase {
            get {
                return ResourceManager.GetString("Setup_ResetDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ATTENZIONE: devo cancellare TUTTO il database?
        ///(Tutti i dati verranno persi!).
        /// </summary>
        public static string Setup_ResetDatabaseConfirm {
            get {
                return ResourceManager.GetString("Setup_ResetDatabaseConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a CANCELLAZIONE.
        /// </summary>
        public static string Setup_ResetDatabaseTitle {
            get {
                return ResourceManager.GetString("Setup_ResetDatabaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Salva database alla chiusura.
        /// </summary>
        public static string Setup_SaveBackupOnExit {
            get {
                return ResourceManager.GetString("Setup_SaveBackupOnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Salva config..
        /// </summary>
        public static string Setup_SaveConfig {
            get {
                return ResourceManager.GetString("Setup_SaveConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Salva configurazione.
        /// </summary>
        public static string Setup_SaveConfiguration {
            get {
                return ResourceManager.GetString("Setup_SaveConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gestione periodi.
        /// </summary>
        public static string Setup_SchoolPeriodsManagement {
            get {
                return ResourceManager.GetString("Setup_SchoolPeriodsManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gestione materie.
        /// </summary>
        public static string Setup_SchoolSubjectManagement {
            get {
                return ResourceManager.GetString("Setup_SchoolSubjectManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gestione start links.
        /// </summary>
        public static string Setup_StartLinksManagement {
            get {
                return ResourceManager.GetString("Setup_StartLinksManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gestione studenti.
        /// </summary>
        public static string Setup_StudentsManagement {
            get {
                return ResourceManager.GetString("Setup_StudentsManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gestione tabelle.
        /// </summary>
        public static string Setup_TablesManagement {
            get {
                return ResourceManager.GetString("Setup_TablesManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gestione tag.
        /// </summary>
        public static string Setup_TagsManagement {
            get {
                return ResourceManager.GetString("Setup_TagsManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gestione prove.
        /// </summary>
        public static string Setup_TestManagement {
            get {
                return ResourceManager.GetString("Setup_TestManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Configurazione.
        /// </summary>
        public static string Setup_Title {
            get {
                return ResourceManager.GetString("Setup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Se abilitato il programma chiede una password per entrare.
        /// </summary>
        public static string Setup_Tooltip_AskPassword {
            get {
                return ResourceManager.GetString("Setup_Tooltip_AskPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Generazione di file e salvataggi di backup.
        /// </summary>
        public static string Setup_Tooltip_BackupManagement {
            get {
                return ResourceManager.GetString("Setup_Tooltip_BackupManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Creazione e modifica delle classi.
        /// </summary>
        public static string Setup_Tooltip_ClassesManagement {
            get {
                return ResourceManager.GetString("Setup_Tooltip_ClassesManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Selezione della lingua dell&apos;interfaccia.
        /// </summary>
        public static string Setup_Tooltip_Language {
            get {
                return ResourceManager.GetString("Setup_Tooltip_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gestione delle domande.
        /// </summary>
        public static string Setup_Tooltip_QuestionManagement {
            get {
                return ResourceManager.GetString("Setup_Tooltip_QuestionManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Confronto fra versioni dell&apos;albero degli argomenti (da completare).
        /// </summary>
        public static string Setup_Tooltip_RecoverTopics {
            get {
                return ResourceManager.GetString("Setup_Tooltip_RecoverTopics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Se abilitato il programma salva un backup del database alla chiusura.
        /// </summary>
        public static string Setup_Tooltip_SaveBackupOnExit {
            get {
                return ResourceManager.GetString("Setup_Tooltip_SaveBackupOnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gestione periodi scolastici (trimestri, quadrimestri..).
        /// </summary>
        public static string Setup_Tooltip_SchoolPeriodsManagement {
            get {
                return ResourceManager.GetString("Setup_Tooltip_SchoolPeriodsManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gestione di link e programmi lanciati all&apos;apertura di una classe.
        /// </summary>
        public static string Setup_Tooltip_StartLinksManagement {
            get {
                return ResourceManager.GetString("Setup_Tooltip_StartLinksManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gestione degli studenti.
        /// </summary>
        public static string Setup_Tooltip_StudentsManagement {
            get {
                return ResourceManager.GetString("Setup_Tooltip_StudentsManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Modifiche delle tabelle dei dati fissi.
        /// </summary>
        public static string Setup_Tooltip_TablesManagement {
            get {
                return ResourceManager.GetString("Setup_Tooltip_TablesManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gestione dei tag associati agli argomenti.
        /// </summary>
        public static string Setup_Tooltip_TagsManagement {
            get {
                return ResourceManager.GetString("Setup_Tooltip_TagsManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gestione dei test (da finire e controllare!).
        /// </summary>
        public static string Setup_Tooltip_TestManagement {
            get {
                return ResourceManager.GetString("Setup_Tooltip_TestManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gestione dell&apos;albero degli argomenti.
        /// </summary>
        public static string Setup_Tooltip_TopicsManagement {
            get {
                return ResourceManager.GetString("Setup_Tooltip_TopicsManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a TODO!.
        /// </summary>
        public static string Setup_Tooltip_UsersManagement {
            get {
                return ResourceManager.GetString("Setup_Tooltip_UsersManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gestione argomenti.
        /// </summary>
        public static string Setup_TopicsManagement {
            get {
                return ResourceManager.GetString("Setup_TopicsManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Usa demo.
        /// </summary>
        public static string Setup_UseDemo {
            get {
                return ResourceManager.GetString("Setup_UseDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gestione Utenti.
        /// </summary>
        public static string Setup_UsersManagement {
            get {
                return ResourceManager.GetString("Setup_UsersManagement", resourceCulture);
            }
        }
    }
}
