<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.18" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.18" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.0.2" />
    <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="9.0.7" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="2.1.11" />
    <PackageReference Include="SQLitePCLRaw.core" Version="2.1.11" />
  </ItemGroup>

  <Import Project="..\BusinessLayer\BusinessLayer.projitems" Label="Shared" />

  <Import Project="..\DataLayer\DataLayer.projitems" Label="Shared" />

  <Import Project="..\SharedBlazor\SharedBlazor.projitems" Label="Shared" />

  <Import Project="..\TreeMpttBlazor\TreeMpttBlazor.projitems" Label="Shared" />

  <Import Project="..\TreeMpttManagement\MpttTreeManagement.projitems" Label="Shared" />

  <Import Project="..\BusinessObjects\BusinessObjects.projitems" Label="Shared" />

  <Import Project="..\SharedItems\SharedItems.projitems" Label="Shared" />

</Project>
