PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

DELETE FROM Answers;
DELETE FROM Answers_Questions;
DELETE FROM Classes;
DELETE FROM Classes_SchoolSubjects;
DELETE FROM Classes_StartLinks;
DELETE FROM Classes_Students;
DELETE FROM Classes_Tests;
--DELETE FROM Flags;
--DELETE FROM GradeCategories;
DELETE FROM Grades;
--DELETE FROM GradeTypes;
DELETE FROM Images;
DELETE FROM Lessons;
DELETE FROM Lessons_Images;
DELETE FROM Lessons_Topics;
DELETE FROM Questions;
DELETE FROM Questions_Tags;
--DELETE FROM QuestionTypes;
DELETE FROM Reminders;
DELETE FROM ReminderTypes;
DELETE FROM SchoolPeriods;
--DELETE FROM SchoolPeriodTypes;
DELETE FROM Schools;
--DELETE FROM SchoolSubjects;
DELETE FROM SchoolYears;
DELETE FROM Students;
DELETE FROM Students_GradeTypes;
DELETE FROM StudentsAnnotations;
DELETE FROM StudentsAnswers;
DELETE FROM StudentsPhotos;
DELETE FROM StudentsPhotos_Students;
DELETE FROM StudentsQuestions;
DELETE FROM StudentsTests;
DELETE FROM StudentsTests_StudentsPhotos;
DELETE FROM Subjects;
DELETE FROM Tags;
DELETE FROM Tests;
DELETE FROM Tests_Questions;
DELETE FROM Tests_Tags;
--DELETE FROM TestTypes;
DELETE FROM Topics; -- this could be commented we we wanted to leave the topics
DELETE FROM Users;
--DELETE FROM UsersCategories;

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
